#!/usr/bin/env sh
set -e

echo "Running style verification..."
dotnet restore backend/dotnet-template.slnx
dotnet format backend/dotnet-template.slnx --verify-no-changes --severity error --no-restore

echo "Running build..."
dotnet build backend/dotnet-template.slnx --nologo --no-restore
