#!/usr/bin/env sh
set -e

echo "Running style verification..."
dotnet restore backend/Template.slnx
dotnet format backend/Template.slnx --verify-no-changes --severity error --no-restore

echo "Running build..."
dotnet build backend/Template.slnx --nologo --no-restore
