FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["src/services/Template.Gateway.Api/Template.Gateway.Api.csproj", "src/services/Template.Gateway.Api/"]
COPY ["src/common/Template.Common/Template.Common.csproj", "src/common/Template.Common/"]
COPY NuGet.Config ./
COPY Directory.Packages.props ./
RUN dotnet restore "src/services/Template.Gateway.Api/Template.Gateway.Api.csproj"
COPY . .
WORKDIR "/src/src/services/Template.Gateway.Api"
RUN dotnet publish -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Template.Gateway.Api.dll"]
