<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Template.Application\Template.Application.csproj" />
    <ProjectReference Include="..\Template.Domain\Template.Domain.csproj" />
    <ProjectReference Include="..\Template.Grpc\Template.Grpc.csproj" />
    <ProjectReference Include="..\..\common\Template.Common.Templating\Template.Common.Templating.csproj" />
    <ProjectReference Include="..\..\common\Template.Common.Email\Template.Common.Email.csproj" />
    <ProjectReference Include="..\..\common\Template.Common.Jobs\Template.Common.Jobs.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Net.ClientFactory" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.IdentityModel.Tokens" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Templates\**\*.scriban" />
  </ItemGroup>

</Project>
